### ISSUE TITLE
Can't start liri

### ISSUE THREAD

**Issue by Howard-00** [lirios/lirios#54]
Unable to query physical screen size, defaulting to 100 dpi.
To override, set QT_QPA_EGLFS_PHYSICAL_WIDTH and QT_QPA_EGLFS_PHYSICAL_HEIGHT (in millimeters).
Cannot mix incompatible Qt library (version 0x50a00) with this library (version 0x50a01)

**Comment by ashvinnihalani** [comment]
I also have this error, on Arch if it matters. However the versions have changed I have the respective versions being 0x50a01 and 0x50b00, I am assuming this is QT 10 and 11. Some additional info is that I can run it windowed in both Xorg, on Gnome, and Wayland, in Weston. It would be nice if you included custom version of QT so that people can use the shell without having downgrade.

**Comment by itay-grudev** [comment]
@plfiorini I'm also getting this and I'm not exactly sure how to solve it. Also on Arch.

**Comment by itay-grudev** [comment]
#44

**Comment by maenpaa24** [comment]
so am I. Both experiencing the error and on arch.

**Comment by rdrms** [comment]
I'm getting this error on Arch Linux (Well, actually Manjaro) with the official liri repository packages

Cannot mix incompatible Qt library (version 0x50a01) with this library (version 0x50b01)

Sounds like the Arch packages need to be rebuilt against the newer version of Qt in the Arch repositories?

**Comment by hughwilliams94** [comment]
Any progress on this issue? I would love to be able to get Liri working again on Arch so that I can start helping with testing.

**Comment by plfiorini** [comment]
This should be working with the AUR packages now.
