### ISSUE TITLE
repo.liri.io does not work

### ISSUE THREAD

**Issue by mispp** [lirios/lirios#59]
```
[root@y2:/home/mspehar]# pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
error: failed retrieving file 'liri-unstable.db' from repo.liri.io : The requested URL returned error: 404
error: failed to update liri-unstable (unexpected error)
error: failed to synchronize all databases
```

[https://repo.liri.io/archlinux/unstable/x86_64/](https://repo.liri.io/archlinux/unstable/x86_64/) is empty

**Comment by plfiorini** [comment]
The repo is being rebuilt

**Comment by plfiorini** [comment]
Besides I'm considering to drop the binary packages, CI is too slow to build anything.
We need a proper server, an Atom CPU can't take it anymore.

**Comment by mispp** [comment]
i have a private server running at home. celeron g1600 (or something like that) that came with hp microserver gen8. if you can give some guidance, i could set it up to be built locally and uploaded. 

or hetzner cloud, they have 3eur month, 1cpu, 2gb machines with 20 tb outgoing traffic.

**Comment by plfiorini** [comment]
Here's how packages are built now:

1. Read [channels.json](https://github.com/lirios/packages/blob/master/channels.json), for example with Python
2. Iterate over the `unstable` list of packages
3. Build each package with this [script](https://github.com/lirios/packages/blob/master/docker-build) that spawns a Docker container with a `/repo` volume that points the directory where the `liri-unstable.db.tar.gz` repository is built and package files are created. See [here](https://github.com/lirios/buildbot-config/blob/master/factories/_archlinux.py#L21)

The Docker container is `liridev/buildbot-archlinux` and it's rebuild every day. It is pretty Buildbot specific because it runs the `buildbot-worker` process automatically.

**Comment by plfiorini** [comment]
Btw even without a binary repository you would be able to build Liri yourself using `pacaur` or whatever AUR tool you like.

**Comment by mispp** [comment]
thanks for the notes, i'll try it out. 
i'm aware that something can be built using aur, but i prefer binary because aur build does not necessarily have to succeed.

where was repo.liri.io previously hosted? 

i could maybe sponsor this with one machine as mentioned before (1cpu core, 2gb ram, 20gb drive) to do builds and host binaries. at least for some time.  and also, building this should not take a lot of time/cpu resourecs or hdd, right?
So:
- would that make sense given that liri is not yet usable?
- how about ubuntu ppa?

**Comment by mispp** [comment]
or maybe google build servers as an alternative?

**Comment by thx1111** [comment]
Pier, while this is going on, please, as a courtesy, update the lirios website, https://liri.io/download/, so that users are no longer directed to a nonexistent
```Server = https://repo.liri.io/archlinux/unstable/$arch/```

Instead, perhaps you could provide a list of the AUR packages in the minimal set of essential packages required to run the liri packages from the Arch Community repository.  Or, maybe there is a single AUR liri git package that already includes the complete dependency list?

**Comment by plfiorini** [comment]
@thx1111  The AUR package you are looking for is `liri-git-meta`

**Comment by thx1111** [comment]
Thanks Pier.

For anyone else reading here, currently there is a QtWayland caused build bug for liri-materialdecoration-git, for which an upstream bug has already been submitted.  Patience...

**Comment by plfiorini** [comment]
@thx1111 You are welcome. I also had changed the download page to mention AUR instead of already built packages.

**Comment by mispp** [comment]
@plfiorini i tried instructions on `lirios/buildbot-config`, but no luck. error pops up about delimiter. 

anyway, as far as i understood, `lirios/buildbot-config` should be used together with buildbot docker container, basically append lirios module (buildbot-config) to the original container and it should automagically pull all the info from github and store results into `/srv/ci/buildbot` 

note: i would assume that git clone mentioned on buildbot-config is wrong, so the actual statement used is: `git clone https://github.com/lirios/buildbot-config.git liribotcfg`

_(i can update the docu there after i make this all work)_

results of cloning and setup look like this:

```
m@hp:~/liri/liribotcfg$ tree
.
├── config.json
├── liribotcfg
│   ├── README.md
│   ├── __init__.py
│   ├── config.json.sample
│   ├── configuration.py
│   ├── factories
│   │   ├── __init__.py
│   │   ├── _archlinux.py
│   │   ├── _docker.py
│   │   ├── _flatpak.py
│   │   ├── _image.py
│   │   └── _ostree.py
│   ├── master.cfg
│   ├── scripts
│   │   └── flatpak-repo.sh
│   └── utils.py
└── master.cfg -> liribotcfg/master.cfg

3 directories, 15 files
```

docker run statement found on the `lirios/buildbot-config` readme should basically work without any changes. unfortunately it doesn't, it complains about:

`exceptions.ValueError: Expecting , delimiter: line 21 column 31 (char 574)`

i would assume that the scripts are set up properly if you used them on forementioned atom server, so any idea what would be the problem here?

config.json is just a copy of config.json.sample

**Comment by plfiorini** [comment]
I was not suggesting to use Buildbot, rather read the code if you need to know how it used to build the packages.

Basically you need to build a package following [the Arch instructions](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_Clean_Chroot) configuring your chroot to use your repository and then after the build, add the resulting package to the repository.
